name: todo-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    name : Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install docker-compose
      run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - name: permissions
      run: sudo chmod +x /usr/local/bin/docker-compose  
    - name: Build the Docker image
      run: docker-compose up -d
    - name: testing
      run: docker exec todoapp sh -c "pytest ."


  Deploy:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} 
    name: Deploy
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Connect and Execute Commands
      uses: appleboy/ssh-action@master
      with:
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          script: |
            sudo -i
            cd ${{secrets.PROJECT_PATH}}
            docker-compose -f docker-compose-stage.yml stop
            git pull
            docker-compose -f docker-compose-stage.yml restart      
